VIA_ENABLE = yes

ENCODER_MAP_ENABLE = yes
AUTO_SHIFT_ENABLE = yes
SWAP_HANDS_ENABLE = yes
COMBO_ENABLE = yes
SEND_STRING = yes

CONSOLE_ENABLE = no
COMMAND_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = yes
MAGIC_ENABLE = no
AVR_USE_MINIMAL_PRINTF = yes
MUSIC_ENABLE = no
